// This file is auto-generated by @hey-api/openapi-ts

export type Feature = {
  /**
   * Auto-generated ID for the feature
   */
  id: string;
  /**
   * Name of the feature
   */
  name: string;
  /**
   * Description of the feature
   */
  description: string;
  /**
   * Status of the feature 'not started' | 'in progress' | 'done'
   */
  status: string;
};

export type GetFeaturesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/features";
};

export type GetFeaturesResponses = {
  /**
   * Features
   */
  200: {
    features?: Array<Feature>;
  };
};

export type GetFeaturesResponse =
  GetFeaturesResponses[keyof GetFeaturesResponses];

export type PostFeaturesData = {
  body: Feature;
  path?: never;
  query?: never;
  url: "/features";
};

export type PostFeaturesResponses = {
  /**
   * Feature added successfully
   */
  201: Feature;
};

export type PostFeaturesResponse =
  PostFeaturesResponses[keyof PostFeaturesResponses];

export type DeleteFeaturesByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/features/{id}";
};

export type DeleteFeaturesByIdResponses = {
  /**
   * Feature removed successfully
   */
  200: unknown;
};

export type ClientOptions = {
  baseUrl: `${string}://${string}/api/v1` | (string & {});
};
