import "@repo/ui/global.scss";
import type { Metadata } from "next";
import "open-props/style"; // https://github.com/GoogleChromeLabs/postcss-jit-props/issues/7
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
